// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddPauseHook() {
  return window['go']['main']['App']['AddPauseHook']();
}

export function GetDofusWindows() {
  return window['go']['main']['App']['GetDofusWindows']();
}

export function GetToggleListenerKeybind() {
  return window['go']['main']['App']['GetToggleListenerKeybind']();
}

export function PauseHook() {
  return window['go']['main']['App']['PauseHook']();
}

export function ResumeHook() {
  return window['go']['main']['App']['ResumeHook']();
}

export function UpdateDofusWindows() {
  return window['go']['main']['App']['UpdateDofusWindows']();
}

export function UpdateDofusWindowsOrder(arg1) {
  return window['go']['main']['App']['UpdateDofusWindowsOrder'](arg1);
}

export function UpdateStatus(arg1) {
  return window['go']['main']['App']['UpdateStatus'](arg1);
}
