// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ActivateAction(arg1) {
  return window['go']['main']['App']['ActivateAction'](arg1);
}

export function ActivateNextChar() {
  return window['go']['main']['App']['ActivateNextChar']();
}

export function ActivatePreviousChar() {
  return window['go']['main']['App']['ActivatePreviousChar']();
}

export function CreateConfigSection(arg1, arg2) {
  return window['go']['main']['App']['CreateConfigSection'](arg1, arg2);
}

export function GetAllKeyBindings() {
  return window['go']['main']['App']['GetAllKeyBindings']();
}

export function GetDofusWindows() {
  return window['go']['main']['App']['GetDofusWindows']();
}

export function GetIndexOfCharacter() {
  return window['go']['main']['App']['GetIndexOfCharacter']();
}

export function GetKeycodes() {
  return window['go']['main']['App']['GetKeycodes']();
}

export function GetToggleListenerKeybind() {
  return window['go']['main']['App']['GetToggleListenerKeybind']();
}

export function IsWindowDofus() {
  return window['go']['main']['App']['IsWindowDofus']();
}

export function KeybindUpdatedEvent() {
  return window['go']['main']['App']['KeybindUpdatedEvent']();
}

export function PauseHook() {
  return window['go']['main']['App']['PauseHook']();
}

export function ResumeHook() {
  return window['go']['main']['App']['ResumeHook']();
}

export function SaveCharacterList(arg1) {
  return window['go']['main']['App']['SaveCharacterList'](arg1);
}

export function SaveKeybind(arg1, arg2, arg3) {
  return window['go']['main']['App']['SaveKeybind'](arg1, arg2, arg3);
}

export function SetAlwaysOnTop() {
  return window['go']['main']['App']['SetAlwaysOnTop']();
}

export function StartHook() {
  return window['go']['main']['App']['StartHook']();
}

export function StopHook() {
  return window['go']['main']['App']['StopHook']();
}

export function UpdateDofusWindows() {
  return window['go']['main']['App']['UpdateDofusWindows']();
}

export function UpdateDofusWindowsOrder(arg1) {
  return window['go']['main']['App']['UpdateDofusWindowsOrder'](arg1);
}

export function UpdateOrder(arg1, arg2) {
  return window['go']['main']['App']['UpdateOrder'](arg1, arg2);
}

export function UpdateOrganizerRunning() {
  return window['go']['main']['App']['UpdateOrganizerRunning']();
}

export function WinActivate(arg1) {
  return window['go']['main']['App']['WinActivate'](arg1);
}
