// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function AddPauseHook():Promise<void>;

export function GetDofusWindows():Promise<Array<main.WindowInfo>>;

export function GetToggleListenerKeybind():Promise<string>;

export function PauseHook():Promise<void>;

export function ResumeHook():Promise<void>;

export function UpdateDofusWindows():Promise<Array<main.WindowInfo>>;

export function UpdateDofusWindowsOrder(arg1:Array<main.WindowInfo>):Promise<void>;

export function UpdateStatus(arg1:string):Promise<void>;
